<?php
/**
 * ApiBase API模块下的公共控制器 不需要登录的场景的继承
 * Author: Chunlai<chunlai0928@foxmail.com>
 * Date: 2020/4/11
 * Time: 15:40
 */
namespace app\api\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController {
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args) {
        throw new HttpResponseException(show(...$args));
    }
}